PREFIX ?= /usr/local
MANPREFIX = ${PREFIX}/share/man
TERMINFO := /usr/share/terminfo

INCS = -I.
LIBS = -lc -lutil -lncurses
CPPFLAGS = -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_XOPEN_SOURCE_EXTENDED
CFLAGS += -std=c99 ${INCS} -DNDEBUG ${CPPFLAGS} -D_DARWIN_C_SOURCE

CC ?= cc
